[application]
environment = "PRODUCTION"
version = "v2.2.0"

[vpn]
binary_path = "/opt/cisco/secureclient/bin/vpn"
gui_path = "/Applications/Cisco/Cisco Secure Client.app/"
connection_retry = 2

[sqlite]
path = "~/.vpnctl/vpnctl.db"

[keyring]
service_name = "vpnctl"
encryption_key = "+7u13LXxwNcInI2UbPLRYA=="

[logger]
level = 1